spring:
  application.name: condo-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${condomanager.db.url}
    username: ${condomanager.db.username}
    password: ${condomanager.db.password}