version: '2'
services:
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: condo-manager
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  postgres-keycloak:
    image: postgres:15.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgresql-keycloak:/var/lib/postgresql/data
  keycloak-export-configuration:
    image: quay.io/keycloak/keycloak:22.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - export
      - --db=postgres
      - --db-url-host=postgres-keycloak
      - --db-username=postgres
      - --db-password=postgres
      - --realm=condo-manager
      - --dir=/opt/keycloak/data/import
    depends_on:
      - postgres-keycloak
    # noinspection ComposeUnknownKeys
    profiles: [ "keycloak-export-configuration"]
    volumes:
      - ./keycloak:/opt/keycloak/data/import
  keycloak-import-configuration:
    image: quay.io/keycloak/keycloak:22.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - import
      - --db=postgres
      - --db-url-host=postgres-keycloak
      - --db-username=postgres
      - --db-password=postgres
      - --dir=/opt/keycloak/data/import
      - --override=true
    depends_on:
      - postgres-keycloak
    volumes:
      - ./keycloak:/opt/keycloak/data/import
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      #- --hostname-strict=false
      #- --hostname-strict-https=false
      #- --http-enabled=true
      - --db=postgres
      - --db-url-host=postgres-keycloak
      - --db-username=postgres
      - --db-password=postgres
    ports:
      - "8081:8080"
    depends_on:
      - postgres-keycloak
      - keycloak-import-configuration
  condo-manager:
    image: condo-manager:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_PROFILES_ACTIVE: local-docker
      SPRING_CONFIG_LOCATION: /config/
    volumes:
      - ../config:/config
    depends_on:
      - postgres
      - postgres-keycloak
      - keycloak-import-configuration
      - keycloak