version: '2'
services:
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: condo-manager
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  condo-mamager:
    image: condo-manager:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_PROFILES_ACTIVE: dev
      CONDOMANAGER_DB_HOST: postgres
