spring:
  application.name: condo-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${condomanager.db.host}:${condomanager.db.port}/${condomanager.db.dbname}
    username: ${condomanager.db.username}
    password: ${condomanager.db.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${condomanager.keycloak.host}/realms/condo-manager

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  config: file:${spring.config.location:config}/logback-spring.xml
  file.path: logs