name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: ScribeMD/docker-cache@0.3.6
        with:
          key: docker-cache-for-build-${{ hashFiles('pom.xml') }}
      - name: Compile, code linting, package and build docker image
        run: ./mvnw -B install -DskipTests
      - name: Save docker image as tar file
        run: docker save condo-manager:latest > /tmp/condo-manager-image.tar
      - name: Put docker image file tar in cache
        uses: actions/cache/save@v3
        with:
          path: /tmp/condo-manager-image.tar
          key: condo-manager-image-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Put maven project artifacts in cache
        uses: actions/cache/save@v3
        with:
          path: ~/.m2/repository/com/ikm/condo-manager
          key: condo-manager-maven-${{ github.run_id }}-${{ github.run_attempt }}
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: ScribeMD/docker-cache@0.3.6
        with:
          key: docker-cache-for-unit-tests-${{ hashFiles('pom.xml') }}
      - name: Run unit tests
        run: ./mvnw -B test -Ddetekt.skip
      - name: Add coverage to PR
        if: github.event_name == 'pull_request'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Code Coverage for unit tests
          update-comment: true

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Restore maven project artifacts from cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.m2/repository/com/ikm/condo-manager
          key: condo-manager-maven-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Restore docker image file tar from cache
        uses: actions/cache/restore@v3
        with:
          path: /tmp/condo-manager-image.tar
          key: condo-manager-image-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true
      - name: Load docker image
        run: docker load < /tmp/condo-manager-image.tar
      - uses: ScribeMD/docker-cache@0.3.6
        with:
          key: docker-cache-for-integration-tests-${{ hashFiles('pom.xml') }}-${{ hashFiles('docker/docker-compose-integration-test.yml') }}
      - name: Run integration tests
        run: |
          ./mvnw compile -pl condo-manager-adapter/condo-manager-adapter-web/
          ./mvnw -B verify -pl condo-manager-test/condo-manager-integration-test/ -DskipUTs -Ddetekt.skip -DskipBuildDocker
      - name: Add coverage to PR
        if: github.event_name == 'pull_request'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/condo-manager-integration-test/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Code Coverage for integration tests
          update-comment: true
      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: 'condo-manager'
          dest: 'logs/integration-test'
      - name: Upload container logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: integration-tests-container-logs
          path: logs/integration-test/*
  publish-docker-image:
    name: Publish docker image
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore docker image file tar from cache
        uses: actions/cache/restore@v3
        with:
          path: /tmp/condo-manager-image.tar
          key: condo-manager-image-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true
      - name: Tag docker image and push it to registry
        run: |
          branch=${{ steps.branch-name.outputs.current_branch }}
          version=$branch
          if [[ "$branch" == "main" ]]; then
            version="latest"
          fi
          if [[ "$branch" == "release" ]]; then
            version=`./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout`
          fi
          imageName=ghcr.io/iliankm/condo-manager/condo-manager:$version
          docker load < /tmp/condo-manager-image.tar
          docker tag condo-manager:latest $imageName
          docker push $imageName
