name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile and code linting
      run: ./mvnw -B verify -DskipTests -DskipBuildDocker

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Run unit tests
          run: ./mvnw -B test

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build docker image and run integration tests
        run: | 
          ./mvnw -B verify -DskipUTs -Ddetekt.skip
          cp logs/integration-test/spring.log /tmp/spring.log
      - name: Upload container logs
        uses: actions/upload-artifact@v3
        with:
          name: integration-tests-container-logs
          path: /tmp/spring.log
