name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile and code linting
      run: ./mvnw -B compile -DskipTests
    - name: Package
      run: ./mvnw -B package -DskipTests -DskipITs -DskipBuildDocker
    - name: Build docker image
      run: ./mvnw spring-boot:build-image -pl condo-manager-spring-boot-app -DskipTests

  unit-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Run unit tests
          run: ./mvnw -B test -DskipITs
  
