name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile and code linting
      run: ./mvnw -B compile -DskipTests
    - name: Package
      run: ./mvnw -B install -DskipTests -DskipITs -DskipBuildDocker
    - name: Build docker image
      run: ./mvnw spring-boot:build-image -pl condo-manager-spring-boot-app -DskipTests
    - name: Export image in a .tar file
      run: docker save condo-manager:latest > /tmp/condo-manager-image.tar
    - name: Upload image .tar file
      uses: actions/upload-artifact@v3
      with:
        name: condo-manager-image
        path: /tmp/condo-manager-image.tar

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Run unit tests
          run: ./mvnw -B test -DskipITs

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Download image .tar file
        uses: actions/download-artifact@v3
        with:
          name: condo-manager-image
          path: /tmp
      - name: Load image in docker
        run: docker load --input /tmp/condo-manager-image.tar
      - name: Run integration tests
        run: |
          ./mvnw -B install -pl condo-manager-adapter/condo-manager-adapter-web -DskipTests 
          ./mvnw -B verify -pl condo-manager-test/condo-manager-integration-test
