name: Merge and tag release

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  merge-release-pr:
    name: Merge release PR
    if: github.event_name == 'pull_request' && github.head_ref == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: Merge PR for the release branch
        run: gh pr merge --merge --subject "Merge release branch for version ${{ inputs.release-version }} in main."
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}