name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'The version to be released'
        default: ''
        required: true
        type: string

jobs:
  authorize:
    name: Authorize the user running the workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check
        if: contains(fromJSON(vars.RELEASE_WORKFLOW_ALLOWED_USERS), github.actor) != true
        run: |
          echo "User ${{ github.actor }} is not authorized to run the workflow."
          exit 1
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: authorize
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release
      - name: Reset release branch onto dev
        run: |
          git fetch origin dev --depth 1
          git reset --hard origin/dev
      - name: Setup git user
        uses: fregante/setup-git-user@v2
      - name: Set project release version
        run: |
          ./mvnw versions:set-property -Dproperty=revision -DnewVersion=${{ inputs.release-version }}
          ./mvnw versions:commit
          git commit -am "Set pom version to ${{ inputs.release-version }}"
          git push --force
      - name: Create PR for the release branch
        run: gh pr create -B main -H release --title "[PR] Merge release branch for version ${{ inputs.release-version }} into main" --body "Created by Github action"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
