name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'The version to be released'
        default: ''
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release
      - name: Reset release branch onto dev
        run: |
          git fetch origin dev --depth 1
          git reset --hard origin/dev
      - name: Setup git user
        uses: fregante/setup-git-user@v2
      - name: Set project release version
        run: |
          ./mvnw versions:set-property -Dproperty=revision -DnewVersion=${{ inputs.release-version }}
          ./mvnw versions:commit
          git commit -am "Set version to ${{ inputs.release-version }}"
          git push --force