name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'The version to be released'
        default: ''
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        shell: bash
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release
      - name: Reset release branch onto dev
        run: |
          git fetch origin dev --depth 1
          git reset --hard origin/dev
      - name: Setup git user
        uses: fregante/setup-git-user@v2
      - name: Set project release version
        run: |
          ./mvnw versions:set-property -Dproperty=revision -DnewVersion=${{ inputs.release-version }}
          ./mvnw versions:commit
          git commit -am "Set version to ${{ inputs.release-version }}"
          git push --force
      - name: Create Pull Request for the release branch
        run: gh pr create -B main -H release --title "Merge release branch into main for version ${{ inputs.release-version }}" --body "Created by Github action"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
